In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def load_dataset(): 
    sales = pd.read_excel("C:/Users/Administrator/Documents/GitHub/titanic/sales.xlsx",header =1)
    view_rate = pd.read_excel("C:/users/Administrator/Documents/GitHub/titanic/view_rate.xlsx",header =1, index_col= 0)
    test = pd.read_excel('test.xlsx',header=1)
    return sales, view_rate, test

sales = load_dataset()[0]
view_rate = load_dataset()[1]
test = load_dataset()[2]

In [3]:
sales_origine =sales.copy()
rating_origine = view_rate.copy()
test_origine = test.copy()

#print( sales.head(), sales.info() )
# sales =  pd.DataFrame(sales_origine)
# view_rate =  pd.DataFrame(rating_origine)
# test =  pd.DataFrame(test_origine)

In [4]:
# 판매단가 > 취급액 이면 취급액 = 0 

def custom(price, total):
    if price > total:
        return 0
    
    else:
        return total

sales["취급액"] = sales.apply(lambda x : custom(x["판매단가"], x["취급액"]), axis=1)

# 확인
# print(sum((sales["판매단가"] > sales["취급액"]) & (sales['취급액'] != 0)))
# sales
# sales.reindex( list(range(len(sales))))

In [5]:
# columne 이름 바꾸기
columnname = { '방송일시' : 's_date', '노출(분)':'during', '마더코드':'mcode', '상품코드':'code','상품명':'name',
          '상품군':'category', '판매단가':'price', '취급액':'sum'}
sales.rename( columns = columnname, inplace = True)
test.rename( columns = columnname, inplace = True)

#sales.head()
#sales.loc[:,'category']

In [6]:
# 결측된 노출분 채우기

for i,row in sales.iterrows():
    val = row["during"]
    if i == 0 :
        continue
        
    if  np.isnan(val):
        if sales.loc[i,"s_date"] == sales.loc[i-1,"s_date"]:
            sales.loc[i,"during"] = sales.loc[i-1,"during"]
        else : 
            continue

            
for i,row in test.iterrows():
    val = row["during"]
    if i == 0 :
        continue
        
    if  np.isnan(val):
        if test.loc[i,"s_date"] == test.loc[i-1,"s_date"]:
            test.loc[i,"during"] = test.loc[i-1,"during"]
        else : 
            continue
            
print(sales.isnull().sum(), test.isnull().sum() )

s_date        0
during        0
mcode         0
code          0
name          0
category      0
price         0
sum         937
dtype: int64 s_date         0
during         0
mcode          0
code           0
name           0
category       0
price          0
sum         2891
dtype: int64

In [234]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37372 entries, 0 to 38303
Data columns (total 14 columns):
s_date      37372 non-null datetime64[ns]
during      37372 non-null timedelta64[ns]
mcode       37372 non-null int64
code        37372 non-null int64
name        37372 non-null object
category    37372 non-null object
price       37372 non-null int64
sum         37372 non-null float64
count       37372 non-null float64
month       37372 non-null int64
day         37372 non-null int64
e_time      37372 non-null object
weekday     37372 non-null int64
sex         37372 non-null int64
dtypes: datetime64[ns](1), float64(2), int64(7), object(3), timedelta64[ns](1)
memory usage: 4.3+ MB

In [7]:
# 무형 Drop
sales.drop(sales[sales["category"]=="무형"].index, inplace=True)
test.drop(test[test["category"]=="무형"].index, inplace=True)

# 판매단가보다 취급액이 적은 경우 Drop
# sales.drop(sales[sales["판매단가"]>=sales["취급액"]].index, inplace = True)

In [8]:
# 마지막 열의 값이 mena일까? 
# test_lst= np.round(np.mean(view_rate.iloc[:,:-1].values,axis=1),3)==view_rate.iloc[:,-1].values
# print(test_lst.all())
# for i in np.argwhere(test_lst ==False):
#     print("{}번째 열들의 평균은 ".format(i))
#     print("마지막 열 직전까지의 값 {}".format(np.mean(view_rate.iloc[i,:-1].values)))
#     print("실제값 : {}\n".format(view_rate.iloc[i,-1].values))

해당 위치에서 mean 값이랑 값이 맞지 않습니다.

In [9]:
# 마지막 열의 값이 mena일까? 
# test_lst= np.round(np.mean(view_rate.iloc[:-1,:].values,axis=0),3)==view_rate.iloc[-1,:].values
# print(test_lst.all())
# for i in np.argwhere(test_lst ==False):
#     print("{}번째 열들의 평균은 ".format(i))
#     print("마지막 열 직전까지의 값 {}".format(np.mean(view_rate.iloc[:-1,i].values)))
#     print("실제값 : {}\n".format(view_rate.iloc[-1,i].values[0]))

In [10]:
# 판매개수 계산
sales['count'] = sales['sum'] / sales['price']
test['count'] = test['sum'] / test['price']

# 판매시간 구분
sales['month'] = sales['s_date'].dt.month
sales['day'] = sales['s_date'].dt.day

test['month'] = test['s_date'].dt.month
test['day'] = test['s_date'].dt.day

sales['during'] = sales['during'].apply(lambda x: datetime.timedelta(minutes=x))  # 한번만 하면 된다.
test['during'] = test['during'].apply(lambda x: datetime.timedelta(minutes=x))

sales['e_time'] = sales['s_date'] + sales['during']
test['e_time'] = test['s_date'] + test['during']
sales['e_time'] = sales['e_time'].dt.time

sales['weekday'] = sales['s_date'].dt.weekday
test['weekday'] = test['s_date'].dt.weekday

def sex(string):
    if '남성' in string:
        dummy = 0
    elif '여성' in string:
        dummy = 1
    else:
        dummy = 2
    
    return dummy

sales['sex'] = sales['name'].apply(sex)
test['sex'] = test['name'].apply(sex)

# for i in range(len(sales)):
#     if sales.loc[i,'category'] == '주방':
#         sales.loc[i,'sex'] = 1

# print(sales.head(), test.head())

#sales.dtypes

In [236]:
from datetime import date 

# 공휴일 처리

hol= ['2019-01-01'
,'2019-02-04'
,'2019-02-05'
,'2019-02-06'
,'2019-03-01'
,'2019-05-05'
,'2019-05-06'
,'2019-05-12'
,'2019-06-06'
,'2019-08-15'
,'2019-09-12'
,'2019-09-13'
,'2019-09-14'
,'2019-10-03'
,'2019-10-09'
,'2019-12-25',
'2020-01-01']

sales["date_string"] = sales["s_date"].apply(lambda x : str(date(x.year,x.month,x.day).isoformat()))

# 1이면 공휴일 아니면 0

sales['holiday']=(sales['date_string'].isin(hol)).astype(int)
sales.head()

,s_date,during,mcode,code,name,category,price,sum,count,month,day,e_time,weekday,sex,date_string,holiday
0,2019-01-01 06:00:00,00:20:00,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0,52.606516,1,1,06:20:00,1,0,2019-01-01,1
1,2019-01-01 06:00:00,00:20:00,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0,109.548872,1,1,06:20:00,1,1,2019-01-01,1
2,2019-01-01 06:20:00,00:20:00,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0,81.754386,1,1,06:40:00,1,0,2019-01-01,1
3,2019-01-01 06:20:00,00:20:00,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0,174.310777,1,1,06:40:00,1,1,2019-01-01,1
4,2019-01-01 06:40:00,00:20:00,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0,167.218045,1,1,07:00:00,1,0,2019-01-01,1

In [11]:
# 간단한 트렌드 확인

# sales.groupby('sex').count()   # 남성 2583행, 여성 1688행, 미분류 33101행
# monthly = pd.DataFrame(sales.groupby('month').sum()['sum'])   # 월별 총 매출액 합계
# weekly = pd.DataFrame(sales.groupby('weekday').mean()['sum'])   # 요일별 평균 매출액
# daily = pd.DataFrame(sales.groupby('day').mean()['sum'])   # 일별 평균 매출액

# fig, axes = plt.subplots(3,1)
# axes[0].bar(monthly.index,monthly['sum'])
# axes[1].plot(weekly.index,weekly['sum'])
# axes[2].plot(daily.index,daily['sum'])

In [12]:
# def eda(table):
#     monthly = pd.DataFrame(table.groupby('month').sum()['sum'])   # 월별 총 매출액 합계
#     weekly = pd.DataFrame(table.groupby('weekday').mean()['sum'])   # 요일별 평균 매출액
#     daily = pd.DataFrame(table.groupby('day').mean()['sum'])   # 일별 평균 매출액

#     fig, axes = plt.subplots(3,1)
#     axes[0].bar(monthly.index,monthly['sum'])
#     axes[1].plot(weekly.index,weekly['sum'])
#     axes[2].plot(daily.index,daily['sum'])
#     return fig, axes

# for i in range(0,11):
#     eda(sales_ca[i])

In [13]:
# # 총매출액, 요일별 평균 매출액, 일별 평균 매출액에 성차가 있는지 확인

# msales = sales[sales['sex'] == 0]
# fsales = sales[sales['sex'] == 1]

# # male 에 대해서
# mmonthly = pd.DataFrame(msales.groupby('month').sum()['sum'])   # 월별 총 매출액 합계
# mweekly = pd.DataFrame(msales.groupby('weekday').mean()['sum'])   # 요일별 평균 매출액
# mdaily = pd.DataFrame(msales.groupby('day').mean()['sum'])   # 일별 평균 매출액

# fig, axes = plt.subplots(3,1)
# axes[0].bar(mmonthly.index,mmonthly['sum'])
# axes[1].plot(mweekly.index,mweekly['sum'])
# axes[2].plot(mdaily.index,mdaily['sum'])

# # female
# fmonthly = pd.DataFrame(fsales.groupby('month').sum()['sum'])   # 월별 총 매출액 합계
# fweekly = pd.DataFrame(fsales.groupby('weekday').mean()['sum'])   # 요일별 평균 매출액
# fdaily = pd.DataFrame(fsales.groupby('day').mean()['sum'])   # 일별 평균 매출액

# fig, axes = plt.subplots(3,1)
# axes[0].bar(fmonthly.index,fmonthly['sum'])
# axes[1].plot(fweekly.index,fweekly['sum'])
# axes[2].plot(fdaily.index,fdaily['sum'])

NameError: name 'axes' is not defined

In [237]:
category_num = {
    '가구' : 0, '가전':1, '건강기능':2, '농수축':3, '생활용품':4, '속옷':5, '의류':6, '이미용':7, '잡화':8, '주방':9, 
'침구':10}
num_category = {
    0 : '가구', 1:'가전', 2:'건강기능', 3:'농수축', 4:'생활용품', 5:'속옷', 6:'의류', 7:'이미용', 8:'잡화', 9:'주방',
    10:'침구'
}

sales_ca = []
test_ca = []

for i in range(0,11):
    arr = test[test['category'] == '{}'.format(num_category[i])].copy()
    test_ca.append( arr )
    
for i in range(0,11):
    arr = sales[sales['category'] == '{}'.format(num_category[i])].copy()
    sales_ca.append( arr )

In [ ]:
# 테스트셋과 트레인셋 간의 데이터 유사도 확인

# name_set = set( sales['name'] )
# t_name_set = set( test['name'])

# code_set = set( sales['code'])
# t_code_set = set( test['code'])

# mcode_set = set( sales['mcode'])
# t_mcode_set = set( test['mcode'])

# category_set = set( sales['category'])
# t_category_set = set( test['category'])

# print("{} - {} = {} : 새로운 상품명".format(len(t_name_set),len(name_set),len(t_name_set - name_set)))
# print("{} - {} = {} : 새로운 상품코드".format(len(t_code_set),len(code_set),len(t_code_set - code_set)))
# print("{} - {} = {} : 새로운 마더코드".format(len(t_mcode_set),len(mcode_set),len(t_mcode_set - mcode_set)))
# print("{} - {} = {} : 새로운 카테고리".format(len(t_category_set),len(category_set),len(t_category_set - category_set)))


# weekly_ca0 = pd.DataFrame(fsales.groupby('weekday').mean()['sum'])   # 요일별 평균 매출액
# daily_ca0 = pd.DataFrame(fsales.groupby('day').mean()['sum'])   # 일별 평균 매출액

# fig, axes = plt.subplots(2,1)
# axes[0].plot(fweekly.index,fweekly['sum'])
# axes[1].plot(fdaily.index,fdaily['sum'])

In [15]:
from konlpy.corpus import kolaw
from konlpy.tag import *

okt = Okt()
hannanum = Hannanum()

# 상품명 리스트로 받기

def tonouns(table):
    name_list = []

    for i,row in table.iterrows():
        name_list.append(row['name'].split(" "))
    
    name_one = [one for one in name_list if len(one) == 1]
    name_two = [one for one in name_list if len(one) != 1]
    name_nouns = [okt.nouns(str(noun)) for noun in name_one]
    
    name_prime = sum(name_nouns + name_two, [])
    
    return name_prime

# 리스트로 받은 상품명, 딕셔너리로 인덱싱

sales_nouns_dict = {}
test_nouns_dict = {}

for i in range(0,11):
    sales_nouns_dict['{}'.format(i)] = tonouns(sales_ca[i])
    test_nouns_dict['{}'.format(i)] = tonouns(test_ca[i])

In [ ]:
# 한글세팅

# from matplotlib import font_manager, rc

# font_name = font_manager.FontProperties(
#     fname="c:/Windows/Fonts/malgun.ttf").get_name()

# rc('font', family=font_name)

#from nltk import Text

# kolaw = Text(name_prime, name='kolaw')
# kolaw.plot(10)
# plt.show()

In [ ]:
# test set 에서 새로운 이름이 등장하는 비율

# def ratio(sales,test):
#     return (len(set(test['name'])-set(sales['name'])))/len(set(test['name']))

# reasonable = []
# for i in range(len(set(sales['category']))):
#     ratio_ = ratio(sales_dict['{}'.format(i)],test_dict['{}'.format(i)])
#     reasonable.append(ratio_)
    
# test set 에서 새로운 명사가 등장하는 비율
    
# def ratio2(sales,test):
#     return (len(set(test)-set(sales)))/len(set(test))

# reasonable2 = []
# for i in range(len(set(sales['category']))):
#     ratio_ = ratio2(sales_nouns_dict['{}'.format(i)],test_nouns_dict['{}'.format(i)])
#     reasonable2.append(ratio_)
    
# print( reasonable, reasonable2)

In [16]:
# 명사 등장 횟수 세기

def nouns_count(seri):
    count={}
    for i in seri:
        try: count[i] += 1
        except: count[i]=1
    return count

count_list_test = []
count_list_sales = []

for i in range(0,11):
    count_list_test.append( nouns_count(test_nouns_dict['{}'.format(i)]) )
    count_list_sales.append( nouns_count(sales_nouns_dict['{}'.format(i)]) )

    
# 등장 횟수 기준으로 정렬

sorted_test = []
sorted_sales = []

for i in range(0,11):
    sorted_test.append( sorted(count_list_test[int('{}'.format(i))], key=lambda x : count_list_test[int('{}'.format(i))][x], reverse = True) )
    sorted_sales.append( sorted(count_list_sales[int('{}'.format(i))], key=lambda x : count_list_sales[int('{}'.format(i))][x], reverse = True) )


# 등장횟수 순위별로 데이터 프레임화

df_test = pd.DataFrame(sorted_test)
df_test = pd.DataFrame.transpose(df_test)
df_sales = pd.DataFrame(sorted_sales)
df_sales = pd.DataFrame.transpose(df_sales)


df_sales.rename( columns = num_category, inplace = True)
df_test.rename( columns = num_category, inplace = True)

In [17]:
# 상품명 카테고리별 하나의 리스트로 묶기(중복허용)

" ".join(test_nouns_dict['1'])

sales_tfidf = []
test_tfidf = []

for i in range(len(set(sales['category']))):
    sales_tfidf.append(" ".join(sales_nouns_dict['{}'.format(i)]))
    test_tfidf.append(" ".join(test_nouns_dict['{}'.format(i)]))

# TF-IDF 라이브러리를 이용한 상품명 벡터화

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_test = TfidfVectorizer().fit(test_tfidf)
tfidf_sales = TfidfVectorizer().fit(sales_tfidf)
tfidf_test.transform(test_tfidf).toarray()
tfidf_sales.transform(sales_tfidf).toarray()

# 벡터에 단어 이름 붙여주기

colname_test = {}
colname_sales = {}

for key in tfidf_test.vocabulary_:
    colname_test[tfidf_test.vocabulary_[key]] = key
    
for key in tfidf_sales.vocabulary_:
    colname_sales[tfidf_sales.vocabulary_[key]] = key

test_tfidf_arr = pd.DataFrame(tfidf_test.transform(test_tfidf).toarray())
test_tfidf_arr.rename( columns = colname_test, inplace = True)

sales_tfidf_arr = pd.DataFrame(tfidf_sales.transform(sales_tfidf).toarray())
sales_tfidf_arr.rename( columns = colname_sales, inplace = True)

test_tfidf_arr = pd.DataFrame.transpose(test_tfidf_arr)
sales_tfidf_arr = pd.DataFrame.transpose(sales_tfidf_arr)

def tfidf_sort(df):
    dd = dict( df[df > 0] )
    dd = sorted(dd, key = lambda x : dd[x], reverse = True)
    return dd

tfidf_t = []
tfidf_s = []

for i in range(0,11):
    tfidf_t.append(tfidf_sort(test_tfidf_arr[i]))
    tfidf_s.append(tfidf_sort(sales_tfidf_arr[i]))
    
tfidf_t = pd.DataFrame(tfidf_t)
tfidf_t = pd.DataFrame.transpose(tfidf_t)
tfidf_t.rename( columns = num_category, inplace = True)

tfidf_s = pd.DataFrame(tfidf_s)
tfidf_s = pd.DataFrame.transpose(tfidf_s)
tfidf_s.rename( columns = num_category, inplace = True)

In [172]:
# tfidf_s 와 tfidf_t 의 공통부문 찾아내기

intersection = []

for i in range(0,11):
    intersection.append(list(set(tfidf_t['{}'.format(num_category[i])]) & set(tfidf_s['{}'.format(num_category[i])])))
    
intersection = pd.DataFrame(intersection)
intersection = pd.DataFrame.transpose(intersection)

In [175]:
intersection[0][:11]

0        싱글
1     led침대
2        소파
3      보루네오
4       피올레
5       6인용
6     천연소가죽
7       유로탑
8      None
9       3인용
10     슬라이딩
Name: 0, dtype: object

In [257]:
# intersection 기준

# one-hot encode

from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

z = []
net = [] # 인코딩 할 단어 개수 정하기

for i in range(0,11):
    z = [x for x in intersection[i] if x is not None]
    z = pd.Series(z)
    net.append(z)

# encoding 함수    

def find(name,index):
    onehot = [ 0 for x in range(len(net[index]))]
    net_dict = dict(net[index])
    new_dict = {}
    for key in net_dict:
        new_dict[net_dict[key]] = key
    
    for word in net[index]:
        if word in name:
            onehot[new_dict[word]] = 1
    
    return onehot


# # < tfidf_t 기준 >

# # one-hot encode
# from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder()

# net = [] # 인코딩 할 단어 개수 정하기

# for i in range(0,11):
#     z = int( len([x for x in test_tfidf_arr[i] if x != 0]))
#     net.append(tfidf_t['{}'.format(num_category[i])][:z])

# # encoding 함수    

# def find(name,index):
#     onehot = [ 0 for x in range(len(net[index]))]
#     net_dict = dict(net[index])
#     new_dict = {}
#     for key in net_dict:
#         new_dict[net_dict[key]] = key
    
#     for word in net[index]:
#         if word in name:
#             onehot[new_dict[word]] = 1
    
#     return onehot

In [218]:
net

[0        싱글
 1     led침대
 2        소파
 3      보루네오
 4       피올레
 5       6인용
 6     천연소가죽
 7       유로탑
 8       3인용
 9      슬라이딩
 10      4인용
 11     슈퍼싱글
 dtype: object, 0        s10jk
 1          화이트
 2          무이자
 3           tv
 4           7형
 5         파워모션
 6         lg전자
 7          냉장고
 8          통돌이
 9           삼성
 10          씽큐
 11         벽걸이
 12         청소기
 13         일시불
 14          lg
 15        tdoz
 16      매직스페이스
 17         세탁기
 18        무풍슬림
 19       울트라hd
 20         선풍기
 21         캐리어
 22    arc07vbc
 23         홈멀티
 24         스탠드
 25         에어컨
 26     tr14wk1
 dtype: object, 0     종근당건강
 1       단하루
 2        구미
 3    생유산균골드
 4       락토핏
 5      뉴트리원
 6      다이어트
 7       일시불
 8       무이자
 9       시즌2
 dtype: object, 0           두유48팩
 1             aac
 2             the
 3            110장
 4          누룽지삼계탕
 5              7팩
 6            멋진밥상
 7          안동간고등어
 8              제주
 9         완도꼬마활전복
 10           바다장어
 11           현대어찬
 12           손질갈치
 13           손질문어
 14             바다
 15           흥양농협
 16            자연산
 17             꽃게
 18           바다먹자
 19            피시원
 20            3kg
 21            오세득
 22            20팩
 23          호두아몬드
 24             능이
 25             8팩
 26            1kg
 27            옥수수
 28             3종
 29            영산포
          ...
 32           유귀열의
 33             옛날
 34             하림
 35             숙성
 36           10kg
 37             햅쌀
 38             9팩
 39           통오징어
 40            11팩
 41            10팩
 42            18미
 43             귀한
 44           갑오징어
 45             갈치
 46             쥐포
 47             세트
 48             굴비
 49           20kg
 50             손질
 51            2kg
 52            맛있는
 53             양념
 54    고칼슘검은콩두유48팩
 55       사용불가미리구운
 56             영광
 57            가자미
 58            홍어회
 59             닭발
 60           포기김치
 61            국내산
 Length: 62, dtype: object, 0        올바로
 1         3단
 2       에어포스
 3        고농축
 4        040
 5        초특가
 6        문어발
 7         대형
 8        화이트
 9       냉수마찰
 10      3d매쉬
 11       무이자
 12      슈퍼싱글
 13       파격가
 14        의자
 15    lg생활건강
 16        ev
 17        안마
 18       스마트
 19      선일금고
 20       1세트
 21        중형
 22       청소기
 23       일시불
 24        매트
 25       노비타
 26      굿프렌드
 27        테크
 28        테팔
 29      무료설치
 30    샤프란아우라
 31        무선
 32        비데
 33     밸런스파워
 34       샤워기
 35        세트
 36       이볼브
 37       시리즈
 38       020
 39      매트리스
 40      good
 41     로봇청소기
 42       2세트
 43       물매트
 44      스트레칭
 45        1개
 46     섬유유연제
 47        a7
 48      퀸사이즈
 49        니봇
 50      플래티늄
 dtype: object, 0          5종
 1          7종
 2         심리스
 3          코튼
 4         브라렛
 5         11종
 6        실크트리
 7        오렐리안
 8         원피스
 9          팬티
 10        무이자
 11         브라
 12      란쥬쉐이퍼
 13        쉐이퍼
 14        브라탑
 15         10
 16        라쉬반
 17        기능성
 18       풍기인견
 19       언더셔츠
 20       루시헨느
 21      몬테밀라노
 22    fc바로셀로나
 23       레이프릴
 24        쉐이핑
 25        데일리
 26        일시불
 27         8종
 28        발레리
 29         2종
 30        패키지
 31       노와이어
 32       스트레치
 33       벨레즈온
 34     브라탑패키지
 35        쿨란쥬
 36        드로즈
 37         6종
 38        트렁크
 39       시그니처
 40      에버라스트
 41         썸머
 42        14종
 43         아키
 44         런닝
 45         란쥬
 46        레이스
 47         푸마
 48         4종
 49         남성
 50       라이크라
 51        12종
 52        레이시
 53         헤드
 54      쿠미투니카
 55       보정팬티
 56         보정
 57        5세트
 58       드라이셀
 59        언더탑
 dtype: object, 0          5종
 1     마르엘라로사티
 2        팬츠3종
 3         풀코디
 4         코몽트
 5         원피스
 6          팬츠
 7         티셔츠
 8         베스트
 9          반팔
 10    크리스티나앤코
 11        pat
 12        기능성
 13       풍기인견
 14        젠트웰
 15         린넨
 16        르까프
 17        마모트
 18       롤업재킷
 19         여성
 20         쉬폰
 21         3종
 22     cerini
 23         by
 24        와이드
 25         2종
 26        패키지
 27        nnf
 28        라운드
 29       4종세트
 30        라라쎄
 31         썸머
 32         세트
 33        레이스
 34         4종
 35         남성
 36         1종
 dtype: object, 0         실크테라피
 1          프리미엄
 2           에센스
 3            골드
 4         슈퍼선스틱
 5            샴푸
 6           더블모
 7           탑뉴스
 8          바바코코
 9            보닌
 10         기초세트
 11    비버리힐스폴로클럽
 12         쑥클렌져
 13       남성기초세트
 14          어성초
 15           참존
 16          패키지
 17       에이유플러스
 18         지이링클
 19           그린
 20         오리지널
 21         클린샤워
 22       젤네일스트립
 23          코즈미
 24          선크림
 25        vonin
 26         엘렌실라
 27          블링썸
 28          에너지
 dtype: object, 0       레노마
 1     에어러닝화
 2        체인
 3       소가죽
 4        숄더
 5        샌들
 6      gg플랩
 7       다이얼
 8       더블g
 9       월드컵
 10     투웨이백
 11       2단
 12       토트
 13       반지
 14      테스토
 15       5g
 16    시스마르스
 17       씨마
 18     2종세트
 19     루이띠에
 20      목걸이
 21      프라다
 22      오델로
 23      토트백
 24       gg
 25      aaa
 26       오버
 27       웨지
 28     클러치백
 29     선글라스
       ...
 43       미듐
 44    칼리베이직
 45      탑핸들
 46       볼륨
 47       팔찌
 48     4종세트
 49      밀덴홀
 50       37
 51    에버라스트
 52       엘르
 53     스니커즈
 54       순금
 55      25g
 56       4종
 57       남성
 58     트레킹화
 59     마이크로
 60       백팩
 61      버킷백
 62     기라로쉬
 63      레터링
 64      컬렉션
 65       구찌
 66      버버리
 67      아가타
 68       1종
 69       양산
 70      슬립온
 71       더블
 72      골드바
 Length: 73, dtype: object, 0        쿠진나이프케어
 1           프리미엄
 2             ih
 3            에버홈
 4          전자레인지
 5            에지리
 6         자동회전냄비
 7            무이자
 8            시즌2
 9            crp
 10          10인용
 11          매직쉐프
 12          기본세트
 13         프리미엄형
 14            qs
 15         텀블러세트
 16         분쇄믹서기
 17        밀폐용기세트
 18            2구
 19            fs
 20           블렌더
 21           락앤락
 22           일시불
 23          스텐큐브
 24          플랫타입
 25          프로피쿡
 26        쿠쿠전기밥솥
 27        에어프라이어
 28            5l
 29            스텐
 30           린나이
 31          비스프리
 32           램프쿡
 33           풀세트
 34          프라이팬
 35          보냉보온
 36            한일
 37           6인용
 38         가스레인지
 39           대용량
 40           올리고
 41          후라이팬
 42         온더테이블
 43           다지기
 44    가스와이드그릴레인지
 45           인덕션
 46         am마카롱
 47           파뷔에
 48       qs107fg
 49            3구
 dtype: object, 0    슈퍼특대형
 1       sk
 2       중형
 3       ss
 4      슈퍼킹
 5       대형
 6      보몽드
 7      특대형
 8     슈퍼싱글
 dtype: object]

In [219]:
for i in range(0,11):
    test_ca[i]['encoding'] = test_ca[i]['name'].apply(lambda x : find(x,i))
    sales_ca[i]['encoding'] = sales_ca[i]['name'].apply(lambda x : find(x,i))

In [ ]:
# tfidf_t.to_csv('/test 상품명 분석.csv',sep=',',na_rep = 'NaN', 
#               encoding = 'euc-kr')
# tfidf_s.to_csv('/sales 상품명 분석.csv',sep=',',na_rep = 'NaN', 
#               encoding = 'euc-kr')

In [42]:
# def f_ilter(i,j,k):
#     return sales_ca[i]['encoding'].iloc[j][k] == 1

# def sig(i,j,k,category_detail):
#     table = sales_ca[i][sales_ca[i]['category_detail'] == '{}'.format(category_detail)].copy()
#     total_mean = de_category['sum'].mean()
#     fmonthly = pd.DataFrame(fsales.groupby('month').sum()['sum'])

In [221]:
def significant(i,j):

    product_in = 0
    n = 1
    product_out = 0
    m = 1
    total = []

    for k in range(0,len(sales_ca[i])):
        if sales_ca[i]['encoding'].iloc[k][j] == 1:
            product_in += sales_ca[i]['count'].iloc[k]
            n += 1
        else:
            product_out += sales_ca[i]['count'].iloc[k]
            m += 1
    if n == 1:
        return 0
    else:
        return abs((product_in/n) - (product_out/m + 1)) / (product_out/m + 1)

In [223]:
sig_fin = []

for i in range(0,11):
    
    sig_ele = []
    
    for j in range(0,len(net[i])):
        
        sig_ele.append(significant(i,j))
        
    sig_fin.append(sig_ele)

sig_fin[0]

[0.8856627371225727,
 0,
 0.5360548184388584,
 0.7373947487281447,
 0.5984622075409066,
 0.8300427526606254,
 0.5984622075409066,
 1.6526604620905858,
 0.7341732867040107,
 0.8678032285399019,
 0.11744060449410432,
 1.1516660770400813]

In [262]:
for i in range(0,11):
    sig_fin[i] = pd.Series(sig_fin[i])
    sig_fin[i].index = net[i]
    sig_fin[i] = sig_fin[i].sort_values(ascending = False)

In [350]:
# 가구 카테고리 특성별 더미화

def category0(name):
    brand = 0
    if '유로탑' in name:
        brand = 1
    elif '슬라이딩' in name:
        brand = 2
    elif '피올레' in name:
        brand = 3
        
    size = 0
    if '6인용' in name:
        size = 1
    elif '3인용' in name:
        size = 2
    elif '4인용' in name:
        size = 3
        
    return [brand, size]
    
sales_ca[0]['brand'] = sales_ca[0]['name'].apply(lambda x : category0(x)[0])
sales_ca[0]['size'] = sales_ca[0]['name'].apply(lambda x : category0(x)[1])

In [289]:
# 가전 카테고리 특성별 더미화

def category1(name):
    brand = 0
    if '캐리어' in name:
        brand = 1
    elif 'LG' in name or 'lg' in name or 'lg전자' in name or 'LG전자' in name:
        brand = 2
    elif '삼성' in name:
        brand = 3
        
    feature = 0
    if '홈멀티' in name:
        feature = 1
    elif '무풍슬림' in name:
        feature = 2
    elif '벽결이' in name:
        feature = 3
    elif '일시불' in name:
        feature = 4
        
    return [brand, feature]
    
sales_ca[1]['brand'] = sales_ca[1]['name'].apply(lambda x : category1(x)[0])
sales_ca[1]['feature'] = sales_ca[1]['name'].apply(lambda x : category1(x)[1])

In [293]:
# 건강기능 카테고리 특성별 더미화

def category2(name):
    brand = 0
    if '뉴트리원' in name:
        brand = 1
    elif '락토핏' in name:
        brand = 2
    elif '종근당' in name:
        brand = 3
        
    feature = 0
    if '시즌2' in name:
        feature = 1
    elif '무이자' in name:
        feature = 2
    elif '다이어트' in name:
        feature = 3

    return [brand, feature]
    
sales_ca[2]['brand'] = sales_ca[2]['name'].apply(lambda x : category2(x)[0])
sales_ca[2]['feature'] = sales_ca[2]['name'].apply(lambda x : category2(x)[1])

In [298]:
# 농수축 카테고리 특성별 더미화

def category3(name):
    brand = 0
    if '영광' in name:
        brand = 1
    elif '하림' in name:
        brand = 2
    elif '유귀열의' in name:
        brand = 3
    elif '오세득' in name:
        brand = 4
    elif '바다먹자' in name:
        brand = 5
        
    feature = 0
    if '포기김치' in name:
        feature = 1
    elif '닭발' in name:
        feature = 2
    elif '홍어회' in name:
        feature = 3
    elif '가자미' in name:
        feature = 4
    elif '굴비' in name:
        feature = 5
    elif '갈치' in name:
        feature = 6
    elif '쥐포' in name:
        feature = 7
    elif '갑오징어' in name:
        feature = 8
    elif '통오징어' in name:
        feature = 9
    elif '햅쌀' in name:
        feature = 10
    elif '옥수수' in name:
        feature = 11
    elif '능이' in name:
        feature = 12
    elif '호두아몬드' in name:
        feature = 13
        
    feature2 = 0
    if '국내산' in name:
        feature2 = 1
    elif '양념' in name:
        feature2 = 2
    elif '맛있는' in name:
        feature2 = 3
    elif '손질' in name:
        feature2 = 4
    elif '귀한' in name:
        feature2 = 5
    elif '옛날' in name:
        feature2 = 6
    elif '자연산' in name:
        feature2 = 7

    return [brand, feature, feature2]
    
sales_ca[3]['brand'] = sales_ca[3]['name'].apply(lambda x : category3(x)[0])
sales_ca[3]['feature'] = sales_ca[3]['name'].apply(lambda x : category3(x)[1])
sales_ca[3]['feature2'] = sales_ca[3]['name'].apply(lambda x : category3(x)[2])

In [302]:
# 생활용품 카테고리 특성별 더미화

def category4(name):
    brand = 0
    if '니봇' in name:
        brand = 1
    elif '이볼브' in name:
        brand = 2
    elif '샤프란' in name:
        brand = 3
    elif '테팔' in name:
        brand = 4
    elif '샤프란' in name:
        brand = 5
    elif '굿프렌드' in name:
        brand = 6
    elif '노비타' in name:
        brand = 7
    elif '선일금고' in name:
        brand = 8
    elif 'LG생활건강' in name:
        brand = 9

        
    feature = 0
    if '섬유유연제' in name:
        feature = 1
    elif '물매트' in name:
        feature = 2
    elif '청소기' in name:
        feature = 3
    elif '매트리스' in name:
        feature = 4
    elif '샤워기' in name:
        feature = 5
    elif '비데' in name:
        feature = 6
    elif '안마' in name:
        feature = 7
        
    feature2 = 0
    if 'good' in name:
        feature2 = 1
    elif '무선' in name:
        feature2 = 2
    elif '무료설치' in name:
        feature2 = 3
    elif '중형' in name:
        feature2 = 4
    elif '파격가' in name:
        feature2 = 5
    elif '무이자' in name:
        feature2 = 6
    elif '슈퍼싱글' in name:
        feature2 = 7

    return [brand, feature, feature2]
    
sales_ca[4]['brand'] = sales_ca[4]['name'].apply(lambda x : category4(x)[0])
sales_ca[4]['feature'] = sales_ca[4]['name'].apply(lambda x : category4(x)[1])
sales_ca[4]['feature2'] = sales_ca[4]['name'].apply(lambda x : category4(x)[2])

In [312]:
# 이미용 카테고리 특성별 더미화

def category7(name):
    brand = 0
    if '블링썸' in name:
        brand = 1
    elif '엘렌실라' in name:
        brand = 2
    elif 'VONIN' in name:
        brand = 3
    elif '비버리힐스' in name:
        brand = 4
    elif '바바코코' in name:
        brand = 5
        
    feature = 0
    if '선크림' in name or '선스틱' in name:
        feature = 1
    elif '패키지' in name:
        feature = 2
    elif '기초세트' in name:
        feature = 3
    elif '샴푸' in name:
        feature = 4
    elif '어성초' in name:
        feature = 5

    return [brand, feature]
    
sales_ca[7]['brand'] = sales_ca[7]['name'].apply(lambda x : category7(x)[0])
sales_ca[7]['feature'] = sales_ca[7]['name'].apply(lambda x : category7(x)[1])

In [325]:
# 잡화 카테고리 특성별 더미화

def category8(name):
    brand = 0
    if '아가타' in name:
        brand = 1
    elif '버버리' in name:
        brand = 2
    elif '구찌' in name:
        brand = 3
    elif '가라로쉬' in name:
        brand = 4
    elif '엘르' in name:
        brand = 5
    elif '프라다' in name:
        brand = 6
    elif '루이띠에' in name:
        brand = 7
        
    feature = 0
    if '골드바' in name:
        feature = 1
    elif '양산' in name:
        feature = 2
    elif '백' in name:
        feature = 3
    elif '트레킹화' in name:
        feature = 4
    elif '순금' in name:
        feature = 5
    elif '스니커즈' in name:
        feature = 6
    elif '팔찌' in name:
        feature = 7
    elif '모자' in name:
        feature = 8
    elif '스카프' in name:
        feature = 9
    elif '장지갑' in name:
        feature = 10
    elif '숄더백' in name:
        feature = 11
    elif '선글라스' in name:
        feature = 12
    elif '클러치백' in name:
        feature = 13
    elif '목걸이' in name:
        feature = 14
    elif '반지' in name:
        feature = 15
        
    feature2 = 0
    if '더블' in name:
        feature2 = 1
    elif '1종' in name:
        feature2 = 2
    elif '남성' in name:
        feature2 = 3
    elif '4종' in name:
        feature2 = 4
    elif '여성' in name:
        feature2 = 5
    elif '세트' in name:
        feature2 = 6

    return [brand, feature, feature2]
    
sales_ca[8]['brand'] = sales_ca[8]['name'].apply(lambda x : category8(x)[0])
sales_ca[8]['feature'] = sales_ca[8]['name'].apply(lambda x : category8(x)[1])
sales_ca[8]['feature2'] = sales_ca[8]['name'].apply(lambda x : category8(x)[2])

In [337]:
# 주방 카테고리 특성별 더미화

def category9(name):
    feature = 0
    if '인덕션' in name:
        feature = 1
    elif '그릴' in name or '가스' in name:
        feature = 2
    elif '후라이팬' in name or '프라이팬' in name:
        feature = 3
    elif '에어프라이어' in name:
        feature = 4
    elif '밥솥' in name:
        feature = 5
    elif '믹서기' in name or '블렌더' in name:
        feature = 6
        
    feature2 = 0
    if '3구' in name:
        feature2 = 1
    elif '대용량' in name:
        feature2 = 2
    elif '6인용' in name:
        feature2 = 3
    elif '보냉보온' in name:
        feature2 = 4
    elif '풀세트' in name:
        feature2 = 5
    elif '스텐' in name:
        feature2 = 6
        
    return [feature, feature2]
    
sales_ca[9]['feature'] = sales_ca[9]['name'].apply(lambda x : category9(x)[0])
sales_ca[9]['feature2'] = sales_ca[9]['name'].apply(lambda x : category9(x)[1])

In [338]:
# 침구 카테고리 특성별 더미화

def category10(name):
    feature = 0
    if '슈퍼싱글' in name or 'SS' in name :
        feature = 1
    elif '특대형' in name:
        feature = 2
    elif '보몽드' in name:
        feature = 3
    elif '대형' in name:
        feature = 4
    elif '슈퍼킹' in name or 'SK' in name:
        feature = 5
    elif '중형' in name:
        feature = 6
    elif '슈퍼특대형' in name:
        feature = 7
        
       
    return feature
    
sales_ca[10]['feature'] = sales_ca[10]['name'].apply(lambda x : category10(x))

In [345]:
for i in range(0,1):
    sales_ca[i].to_csv('C:/Users/Administrator/Documents/GitHub/titanic/kchanyoung/sales 카테고리별 상품명 분석.csv'
                       ,sep=',',na_rep = 'NaN', encoding = 'euc-kr')

ImportError: cannot import name 'get_compression_method'

In [348]:
tfidf_s

,가구,가전,건강기능,농수축,생활용품,속옷,의류,이미용,잡화,주방,침구
0,보루네오,lg,종근당건강,8팩,일월,푸마,남성,남성기초세트,루이띠에,쿠쿠전기밥솥,보몽드
1,침대,tv,락토핏,국내산,온수매트,패키지,3종,비버리힐스폴로클럽,프라다,10인용,침구세트
2,led,울트라hd,생유산균골드,20팩,품안애,드로즈,여성,골드,18k,6인용,시어서커
3,유로탑,무이자,단하루,안동간고등어,ev,브라팬티,swiss,2018fw골드,소가죽,일시불,리플
4,멀티수납형,일시불,석류,손질,선일금고,드라이셀,뱅뱅,기초세트,코치,무이자,샐비어
5,삼익가구,삼성,루테인,20kg,시리즈,트렁크,썸머,지이링클,삭루츠,쿠첸,자수
6,소파,에어컨,농부의,멋진밥상,이볼브,심리스,헤스티지,참존,월드컵,압력밥솥,엘사
7,천연소가죽,lg전자,닥터,흥양농협,노비타,오모떼,마르엘라로사티,탑뉴스,여성,a1,ss
8,피올레,냉장고,뉴트리원,aab의,비데,10,데님팬츠,콜라겐,가이거,풀스텐,sk
9,서랍형,uhd,다이어트,800g,무선,4종,19,엘렌실라,토트백,qs,슈퍼킹
10,제니비,매직스페이스,구미,소곱창전골,무이자,레이스,nnf,플라,남성,대용량,더블착번극세사
11,루나,세탁기,정직한,유귀열의,일시불,컬럼비아,cerini,vonin,베르니아,스텐,카밀라
12,led침대,통돌이,100,피시원,2019년,에버라스트,pat,보닌,크로스백,가스레인지,토퍼침구세트
13,루나시즌2,65uk6800hnc,슈퍼,귀한,무료설치,헤드,2종,선크림,숄더백,린나이,효재
14,슈퍼싱글,55uk6800hnc,무이자,손질갑오징어,싱글,레이프릴,4종,플라센타아이크림,2종,자동불꽃조절,소프트플란넬
15,3인용,휘센,일시불,7팩,예초기,라이크라,임페리얼,에스까르고에센스,다이아몬드,신제품,슈퍼싱글
16,4인용,70uk7400kna,4박스,9팩,충전식,풍기인견,by,커버쿠션,워치,분쇄믹서기,광목
17,수납형,노트북,아이클리어,모시떡,타이거,리복,롱코트,실크테라피,도스문도스,올리고,착번아웃
18,어블러,nt900x5j,직매입,영광,020,코튼,보코,에센스,엠보,프리미엄형,카페트
19,ss,메탈,프리바이오틱스,11팩,040,쉐이핑,밍크,네오젠,카이만,19년,헤르만
20,멀티,씽큐,석류즙,녹용도가니탕,카페트매트,아키,uspa,리프트,팔찌,한일,극세사
21,6인용,75uk6200knb,5박스,임성근의,스마트,10종,2019,링클,목걸이,에어프라이어,워싱
22,한샘,벽걸이에어컨,90봉,동부기피70개,바로바로,쿠미투니카,그렉노먼,에이지큐어,선글라스,에코라믹,순면60수
23,장수흙침대,대우전자,무농약레드비트즙,손질문어,에너지세이브,12종,폴로셔츠,원미닛,트레킹화,냄비세트,피그먼트워싱
24,2m,캐리어,84포,총6kg,국내제조,카파,크리스티나앤코,스포메틱스,2019,스톤,레일
25,붙박이장,벽걸이,루비,청정수산,리빙박스,풀커버,팬츠,립스틱,아가타,통주물,암막커튼
26,hg,2in1형,오메가3,자연산,뉴스파,파이로라이트,휘메일,패키지,순금,파뷔에,엘리
27,실버슬림,k14,착즙한,포기김치,무선청소기,라쉬반,패딩,마리끌레르,1종,2구,클라라
28,내추럴,k28,통째로,완도활전복,1개,프레쉬,헤비추얼,파리컬렉션,샌들,3구,호텔식
29,장수,fq17v9kwa2,리얼착즙석류,깐깐송도순,온열매트,동내의,티셔츠,하이드로,워킹화,매직쉐프,세트
...,...,...,...,...,...,...,...,...,...,...,...
344,None,None,None,오리지널,None,None,None,None,가죽,None,None
345,None,None,None,6종,None,None,None,None,린넨,None,None
346,None,None,None,new,None,None,None,None,14k골드,None,None
347,None,None,None,간장전복장2통,None,None,None,None,robe,None,None
348,None,None,None,구이,None,None,None,None,골드파일,None,None
349,None,None,None,완도활전복세트,None,None,None,None,남성트레일화,None,None
350,None,None,None,자숙찰골뱅이,None,None,None,None,노벨라백,None,None
351,None,None,None,None,None,None,None,None,로베,None,None
352,None,None,None,None,None,None,None,None,카로,None,None
353,None,None,None,None,None,None,None,None,트레일화,None,None
354,None,None,None,None,None,None,None,None,ars,None,None
355,None,None,None,None,None,None,None,None,9종,None,None
356,None,None,None,None,None,None,None,None,베스트,None,None
357,None,None,None,None,None,None,None,None,3d,None,None
358,None,None,None,None,None,None,None,None,라이트숄더백,None,None
359,None,None,None,None,None,None,None,None,밍크니팅모자세트,None,None
360,None,None,None,None,None,None,None,None,밍크머플러세트,None,None
361,None,None,None,None,None,None,None,None,쁘띠,None,None
362,None,None,None,None,None,None,None,None,스톨라,None,None
363,None,None,None,None,None,None,None,None,울버튼,None,None
364,None,None,None,None,None,None,None,None,입체,None,None
365,None,None,None,None,None,None,None,None,집어라운드,None,None
366,None,None,None,None,None,None,None,None,총6종,None,None
367,None,None,None,None,None,None,None,None,케이프,None,None
368,None,None,None,None,None,None,None,None,피오레,None,None
369,None,None,None,None,None,None,None,None,아동,None,None
370,None,None,None,None,None,None,None,None,풀스킨,None,None
371,None,None,None,None,None,None,None,None,라이트,None,None
372,None,None,None,None,None,None,None,None,클래식,None,None
373,None,None,None,None,None,None,None,None,볼륨,None,None

In [353]:
sales_ca[0].to_csv

,s_date,during,mcode,code,name,category,price,sum,count,month,day,e_time,weekday,sex,date_string,holiday,brand,size
2952,2019-02-01 22:00:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,7399000.0,13.501825,2,1,22:20:00,4,2,2019-02-01,0,1,0
2953,2019-02-01 22:00:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,3264000.0,5.458194,2,1,22:20:00,4,2,2019-02-01,0,1,0
2954,2019-02-01 22:00:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,5271000.0,8.134259,2,1,22:20:00,4,2,2019-02-01,0,1,0
2955,2019-02-01 22:20:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,20638000.0,37.660584,2,1,22:40:00,4,2,2019-02-01,0,1,0
2956,2019-02-01 22:20:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,17701000.0,29.600334,2,1,22:40:00,4,2,2019-02-01,0,1,0
2957,2019-02-01 22:20:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,17437000.0,26.908951,2,1,22:40:00,4,2,2019-02-01,0,1,0
2958,2019-02-01 22:40:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,32415000.0,59.151460,2,1,23:00:00,4,2,2019-02-01,0,1,0
2959,2019-02-01 22:40:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,33761000.0,56.456522,2,1,23:00:00,4,2,2019-02-01,0,1,0
2960,2019-02-01 22:40:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,31361000.0,48.396605,2,1,23:00:00,4,2,2019-02-01,0,1,0
3231,2019-02-04 20:00:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,8874000.0,16.193431,2,4,20:20:00,0,2,2019-02-04,1,1,0
3232,2019-02-04 20:00:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,1654000.0,2.765886,2,4,20:20:00,0,2,2019-02-04,1,1,0
3233,2019-02-04 20:00:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,3532000.0,5.450617,2,4,20:20:00,0,2,2019-02-04,1,1,0
3234,2019-02-04 20:20:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,11814000.0,21.558394,2,4,20:40:00,0,2,2019-02-04,1,1,0
3235,2019-02-04 20:20:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,12891000.0,21.556856,2,4,20:40:00,0,2,2019-02-04,1,1,0
3236,2019-02-04 20:20:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,19187000.0,29.609568,2,4,20:40:00,0,2,2019-02-04,1,1,0
3237,2019-02-04 20:40:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,33882000.0,61.828467,2,4,21:00:00,0,2,2019-02-04,1,1,0
3238,2019-02-04 20:40:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,25735000.0,43.035117,2,4,21:00:00,0,2,2019-02-04,1,1,0
3239,2019-02-04 20:40:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,33108000.0,51.092593,2,4,21:00:00,0,2,2019-02-04,1,1,0
3486,2019-02-06 23:00:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,8871000.0,16.187956,2,6,23:20:00,2,2,2019-02-06,1,1,0
3487,2019-02-06 23:00:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,12886000.0,21.548495,2,6,23:20:00,2,2,2019-02-06,1,1,0
3488,2019-02-06 23:00:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,7007000.0,10.813272,2,6,23:20:00,2,2,2019-02-06,1,1,0
3489,2019-02-06 23:20:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,35330000.0,64.470803,2,6,23:40:00,2,2,2019-02-06,1,1,0
3490,2019-02-06 23:20:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,17703000.0,29.603679,2,6,23:40:00,2,2,2019-02-06,1,1,0
3491,2019-02-06 23:20:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,17448000.0,26.925926,2,6,23:40:00,2,2,2019-02-06,1,1,0
3492,2019-02-06 23:40:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,27989000.0,51.074818,2,6,00:00:00,2,2,2019-02-06,1,1,0
3493,2019-02-06 23:40:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,28940000.0,48.394649,2,6,00:00:00,2,2,2019-02-06,1,1,0
3494,2019-02-06 23:40:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,22658000.0,34.966049,2,6,00:00:00,2,2,2019-02-06,1,1,0
3681,2019-02-08 21:00:00,00:20:00,100205,200733,보루네오 루나 유로탑 멀티수납형 LED 침대 SS 슈퍼싱글,가구,548000,13278000.0,24.229927,2,8,21:20:00,4,2,2019-02-08,0,1,0
3682,2019-02-08 21:00:00,00:20:00,100205,200732,보루네오 루나 유로탑 멀티수납형 LED 침대 Q 퀸,가구,598000,4865000.0,8.135452,2,8,21:20:00,4,2,2019-02-08,0,1,0
3683,2019-02-08 21:00:00,00:20:00,100205,200731,보루네오 루나 유로탑 멀티수납형 LED 침대 K 킹,가구,648000,5271000.0,8.134259,2,8,21:20:00,4,2,2019-02-08,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37294,2019-12-20 23:00:00,00:20:00,100373,201192,(무)장수흙침대 퀸,가구,1490000,28633000.0,19.216779,12,20,23:20:00,4,2,2019-12-20,0,0,0
37295,2019-12-20 23:00:00,00:20:00,100373,201193,(일)장수 클래식 흙카우치,가구,1520000,12748000.0,8.386842,12,20,23:20:00,4,2,2019-12-20,0,0,0
37296,2019-12-20 23:00:00,00:20:00,100373,201188,(무)장수 클래식 흙카우치,가구,1690000,14365000.0,8.500000,12,20,23:20:00,4,2,2019-12-20,0,0,0
37559,2019-12-23 23:20:00,00:20:00,100373,201196,(일)장수흙침대 싱글,가구,1120000,16787000.0,14.988393,12,23,23:40:00,0,2,2019-12-23,0,0,0
37560,2019-12-23 23:20:00,00:20:00,100373,201191,(무)장수흙침대 싱글,가구,1290000,0.0,0.000000,12,23,23:40:00,0,2,2019-12-23,0,0,0
37561,2019-12-23 23:20:00,00:20:00,100373,201197,(일)장수흙침대 퀸,가구,1320000,14122000.0,10.698485,12,23,23:40:00,0,2,2019-12-23,0,0,0
37562,2019-12-23 23:20:00,00:20:00,100373,201192,(무)장수흙침대 퀸,가구,1490000,9298000.0,6.240268,12,23,23:40:00,0,2,2019-12-23,0,0,0
37563,2019-12-23 23:20:00,00:20:00,100373,201193,(일)장수 클래식 흙카우치,가구,1520000,0.0,0.000000,12,23,23:40:00,0,2,2019-12-23,0,0,0
37564,2019-12-23 23:20:00,00:20:00,100373,201188,(무)장수 클래식 흙카우치,가구,1690000,0.0,0.000000,12,23,23:40:00,0,2,2019-12-23,0,0,0
37565,2019-12-23 23:40:00,00:20:00,100373,201196,(일)장수흙침대 싱글,가구,1120000,7168000.0,6.400000,12,23,00:00:00,0,2,2019-12-23,0,0,0
37566,2019-12-23 23:40:00,00:20:00,100373,201191,(무)장수흙침대 싱글,가구,1290000,5524000.0,4.282171,12,23,00:00:00,0,2,2019-12-23,0,0,0
37567,2019-12-23 23:40:00,00:20:00,100373,201197,(일)장수흙침대 퀸,가구,1320000,25094000.0,19.010606,12,23,00:00:00,0,2,2019-12-23,0,0,0
37568,2019-12-23 23:40:00,00:20:00,100373,201192,(무)장수흙침대 퀸,가구,1490000,6382000.0,4.283221,12,23,00:00:00,0,2,2019-12-23,0,0,0
37569,2019-12-23 23:40:00,00:20:00,100373,201193,(일)장수 클래식 흙카우치,가구,1520000,3280000.0,2.157895,12,23,00:00:00,0,2,2019-12-23,0,0,0
37570,2019-12-23 23:40:00,00:20:00,100373,201188,(무)장수 클래식 흙카우치,가구,1690000,3645000.0,2.156805,12,23,00:00:00,0,2,2019-12-23,0,0,0
37571,2019-12-24 00:00:00,00:20:00,100373,201196,(일)장수흙침대 싱글,가구,1120000,7168000.0,6.400000,12,24,00:20:00,1,2,2019-12-24,0,0,0
37572,2019-12-24 00:00:00,00:20:00,100373,201191,(무)장수흙침대 싱글,가구,1290000,0.0,0.000000,12,24,00:20:00,1,2,2019-12-24,0,0,0
37573,2019-12-24 00:00:00,00:20:00,100373,201197,(일)장수흙침대 퀸,가구,1320000,41820000.0,31.681818,12,24,00:20:00,1,2,2019-12-24,0,0,0
37574,2019-12-24 00:00:00,00:20:00,100373,201192,(무)장수흙침대 퀸,가구,1490000,19075000.0,12.802013,12,24,00:20:00,1,2,2019-12-24,0,0,0
37575,2019-12-24 00:00:00,00:20:00,100373,201193,(일)장수 클래식 흙카우치,가구,1520000,9741000.0,6.408553,12,24,00:20:00,1,2,2019-12-24,0,0,0
37576,2019-12-24 00:00:00,00:20:00,100373,201188,(무)장수 클래식 흙카우치,가구,1690000,7240000.0,4.284024,12,24,00:20:00,1,2,2019-12-24,0,0,0
38262,2019-12-31 19:20:00,00:20:00,100594,201819,레스토닉 블루투스 LED 서랍 침대 슈퍼싱글,가구,599000,1357000.0,2.265442,12,31,19:40:00,1,2,2019-12-31,0,0,0
38263,2019-12-31 19:20:00,00:20:00,100594,201821,레스토닉 블루투스 LED 서랍 침대 퀸,가구,649000,4300000.0,6.625578,12,31,19:40:00,1,2,2019-12-31,0,0,0
38264,2019-12-31 19:20:00,00:20:00,100594,201823,레스토닉 블루투스 LED 서랍 침대 킹,가구,699000,9205000.0,13.168813,12,31,19:40:00,1,2,2019-12-31,0,0,0
38265,2019-12-31 19:40:00,00:20:00,100594,201819,레스토닉 블루투스 LED 서랍 침대 슈퍼싱글,가구,599000,7900000.0,13.188648,12,31,20:00:00,1,2,2019-12-31,0,0,0
38266,2019-12-31 19:40:00,00:20:00,100594,201821,레스토닉 블루투스 LED 서랍 침대 퀸,가구,649000,12803000.0,19.727273,12,31,20:00:00,1,2,2019-12-31,0,0,0
38267,2019-12-31 19:40:00,00:20:00,100594,201823,레스토닉 블루투스 LED 서랍 침대 킹,가구,699000,12259000.0,17.537911,12,31,20:00:00,1,2,2019-12-31,0,0,0
38268,2019-12-31 20:00:00,00:20:00,100594,201819,레스토닉 블루투스 LED 서랍 침대 슈퍼싱글,가구,599000,17044000.0,28.454090,12,31,20:20:00,1,2,2019-12-31,0,0,0
38269,2019-12-31 20:00:00,00:20:00,100594,201821,레스토닉 블루투스 LED 서랍 침대 퀸,가구,649000,9966000.0,15.355932,12,31,20:20:00,1,2,2019-12-31,0,0,0
38270,2019-12-31 20:00:00,00:20:00,100594,201823,레스토닉 블루투스 LED 서랍 침대 킹,가구,699000,27526000.0,39.379113,12,31,20:20:00,1,2,2019-12-31,0,0,0

In [355]:
sales_ca[0].to_excel('/sales_ca.xlxs', # directory and file name to write

            sheet_name = 'Sheet1', 

            na_rep = 'NaN', 

            float_format = "%.2f", 

            header = True, 

            #columns = ["group", "value_1", "value_2"], # if header is False

            #index = True, 

            #index_label = "id", 

            #startrow = 1, 

            #startcol = 1, 

            #engine = 'xlsxwriter', 

            #freeze_panes = (2, 0)

            )

ImportError: cannot import name 'stringify_path'

In [356]:
import pandas as pd

In [346]:
from fbprophet import Prophet

ImportError: cannot import name 'easter'

In [ ]:
df = pd.read_csv("prophet.csv")

df["ds"] = pd.to_datetime(df["ds"])

df['cap'] = 50
df['floor'] = 0

m = Prophet(growth='logistic')   ### 상한,하한이 있을 때는 growth = 'logistic'

### if __name__ == '__main__':  다른 파일에서 import 될 때와 main 함수일 때를 구분

m.fit(df)

future = m.make_future_dataframe(periods=14 )
future.tail()

future['cap'] = 50
future['floor'] = 0

forecast = m.predict(future)
forecast.tail()
forecast[['ds','yhat','yhat_lower','yhat_upper']].tail(14)

fig1 = m.plot(forecast)
fig2 = m.plot_components(forecast)

"""
### Trend Change Points

### Changepoint_range
m = Prophet(changepoint_range = 0.9)

### Changepoint_prior_scale
m = Prophet( changepoint_prior_scale = 0.05)

### changepoint
m = Prophet( changepoints = ['2019-02-04'. '2019-02-05'] )

###시각화
from fbprophet.plot import add_changepoints_to_plot

fig = m.plot(forecast)
a = add.changepoints_to_plot(fig.gca(), m, forecast)
"""

In [231]:
from sklearn.datasets import make_regression
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold

C:\ProgramData\Anaconda3\lib\site-packages\distributed\config.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config.update(yaml.load(text) or {})

In [ ]:
# Dataset
X = sales[['price', 'during','cat_code']].values.reshape(-1,3)
y = sales['count'].values

In [ ]:
models = {
        'Linear Regression': LinearRegression(),
        'LGBM': LGBMRegressor(),
        'XGBoost': XGBRegressor(objective='reg:squarederror'),
        'Random Forest': RandomForestRegressor(max_depth=2, random_state=0)
}
for key, value in models.items():
    print(key)
    model = value
    cv = RepeatedKFold(n_splits=5, n_repeats=2, random_state=1)
    n_scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1, error_score='raise')
    print('MAE: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))
    n_scores = cross_val_score(model, X, y, scoring='r2', cv=cv, n_jobs=-1, error_score='raise')
    print('R2: {:.2f}'.format(mean(n_scores)))

판매액 분석

노출시간과 시청률 ~ 시청률에서 상품구매건수로 가는 비율
시계열 데이터 ~ 요일/ 날짜/ 
상품품목 ~ 원래 팔리던 수준(전체상품대비/같은카테고리대비
          /같은마더코드대비). 성별. 상품가격
          상품 세부 분류가 필요하다면 : 카테고리 > 
          클러스터링
날씨 ~ 미세먼지/강수량/온도

6월특성 ~ 에어컨, 

특수상황
코로나 ~ 마스크, 손세정제

탐색적 데이터 분석
월별 카테고리 비중 변화는 크지 않다.
저녁시간전 농수축 구매량의 증가한다.
저녁시간 이후 가전 구매비율이 증가한다.


상품명 분석

'가구'
(

'가전'
(일시불여부, 브랜드, 종류

'건강기능'
(브랜드, 소비대상, '직매입',

'농수축'
(원산지, 종류, '햅'

'생활용품'
(

'속옷'
(브랜드, 성별, 속옷종류, '시즌i'

'의류'
(브랜드, 성별, 의류종류, '시즌'

'이미용'
(

'잡화'
(

'주방'
(브랜드, 종류, '대용량', '세트', 

'침구'

NLP trained word vector
most similar data 

카테고리별로 먼저 단어별로 분류한후 카운트

상품명은 같은데 상품코드가 다른경우,
상품코드가 같은데 상품명이 다른경우,

작년과의 데이터 차이에 집중
20년에만 등장하는 단어 구별
단어선택할때 매출을 가중치로 사용

여름에 많이 나오는 단어가 6월에 미리 등장하지 않을까?
장마철 ~ 침구류, 매트

50분에 시청률이 튀지 않을까

clustering ~ 

속옷에서 남성 여성 분류하여 feature engnearing
의류에서 남성 여성 분류가능한가. 블라우스. 

카테고리별 상품이 새로 등장했을 때(신상품)
잡아낼 수 있는지. 알아보자.


6월 데이터에 비슷한 단어 찾아보기 most simillar (6월 데이터)
similar 한 상품들만 이용해서 학습진행

카테고리 별. 예측. 어떻게 묶을 것인가.

주가와 ROE, 

fbProphet